[package]
name = "mech-bun"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {version = "1.0.75", features = ["backtrace"]}
crossterm = "0.27.0"
scopeguard = "1.2.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
strum = "0.25.0"
strum_macros = "0.25.2"
